services:
  postgres:
    image: postgres:16-alpine
    container_name: rahyar-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: rahyar
      POSTGRES_USER: rahyar
      POSTGRES_PASSWORD: rahyar
    ports:
      - "5432:5432"
    volumes:
      - rahyar_pgdata:/var/lib/postgresql/data
volumes:
  rahyar_pgdata:
